######################## default configuration ####################
baseURL = "https://day1hpc.com/"
title = "Day 1 HPC"
theme = "logbook-hugo"
# post pagination
[pagination]
pagerSize = 8
# post excerpt
summaryLength = "140"
# google analytics
googleAnalytics = "" # Ex: UA-123-45
# disqus short name
# disqusShortname = "themefisher-template" # get your shortname form here : https://disqus.com
# disable language
disableLanguages = ["fr"] # desable language from here

# Temporary
enableRobotsTXT = true

# Longer to allow complex pages
timeout = "30000"

# Tags
# disableKinds = ["taxonomy", "term"]

# [taxonomies]
#     category = "categories"
#     tag = "tags"

############################# Modules ##############################
[module]
[module.hugoVersion]
extended = true
min = "0.149.0"

############################# Outputs ##############################
[outputs]
home = ["HTML", "RSS", "JSON", "WebAppManifest"]

############################# Imaging ##############################
[imaging]
# See https://github.com/disintegration/imaging
# Default JPEG or WebP quality setting. Default is 75.
quality = 75


############################# Caches ###############################
[caches]
[caches.images]
dir = ":resourceDir/_gen"
maxAge = "720h"

[caches.assets]
dir = ":resourceDir/_gen"
maxAge = "720h"

############################# Markup ###############################
[markup]
[markup.goldmark.renderer]
unsafe = true

[markup.highlight]
style = 'monokai' # see https://xyproto.github.io/splash/docs/all.html

############################ Media types ############################
[mediaTypes]
[mediaTypes."application/manifest+json"]
suffixes = ["webmanifest"]

[mediaTypes."text/netlify"]
delimiter = ""
suffixes = [""]


############################ Output Format ###########################
[outputFormats]
[outputFormats.WebAppManifest]
mediaType = "application/manifest+json"
rel = "manifest"

[params]
# Taxonomies
categories = ["AWS Batch", "AWS ParallelCluster", "Elastic Fabric Adapter", "NICE DCV", "AI/ML", "CAE/CFD", "Financial Services", "Climate/Environment/Weather", "Life Sciences"]

twitter_cards = true
